# This file is part of libtcspc
# Copyright 2019-2026 Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: MIT

from ._access import Accessible, AccessTag
from ._acquisition_readers import AcquisitionReader, NullReader, StuckReader
from ._bucket_sources import (
    BucketSource,
    NewDeleteBucketSource,
    RecyclingBucketSource,
)
from ._codegen import CodeGenerationContext
from ._compile import CompiledGraph, compile_graph
from ._cpp_utils import (
    CppClassScopeDefs,
    CppExpression,
    CppFunctionScopeDefs,
    CppIdentifier,
    CppNamespaceScopeDefs,
    CppTypeName,
    ModuleCodeFragment,
    byte_type,
    contains_type,
    float32_type,
    float64_type,
    identifier_from_string,
    int8_type,
    int16_type,
    int32_type,
    int64_type,
    is_same_type,
    quote_string,
    run_cpp_prog,
    size_type,
    string_type,
    uint8_type,
    uint16_type,
    uint32_type,
    uint64_type,
)
from ._data_types import DataTypes
from ._events import (
    BHSPCEvent,
    BucketEvent,
    DataLostEvent,
    EventType,
    MarkerEvent,
    TimeCorrelatedDetectionEvent,
    TimeReachedEvent,
    WarningEvent,
)
from ._execute import (
    EndOfProcessing,
    ExecutionContext,
    PySink,
    create_execution_context,
)
from ._graph import Graph, Subgraph
from ._node import Node, RelayNode, TypePreservingRelayNode
from ._param import Param, Parameterized
from ._processors import (
    Acquire,
    Batch,
    CheckMonotonic,
    Count,
    DecodeBHSPC,
    NullSink,
    NullSource,
    ReadBinaryStream,
    SelectAll,
    SinkEvents,
    Stop,
    StopWithError,
    Unbatch,
    read_events_from_binary_file,
)
from ._streams import BinaryFileInputStream, InputStream
from ._version import __version__ as __version__

__all__ = [
    "AccessTag",
    "Accessible",
    "Acquire",
    "AcquisitionReader",
    "BHSPCEvent",
    "Batch",
    "BinaryFileInputStream",
    "BucketEvent",
    "BucketSource",
    "CheckMonotonic",
    "CodeGenerationContext",
    "CompiledGraph",
    "Count",
    "CppClassScopeDefs",
    "CppExpression",
    "CppFunctionScopeDefs",
    "CppIdentifier",
    "CppNamespaceScopeDefs",
    "CppTypeName",
    "DataLostEvent",
    "DataTypes",
    "DecodeBHSPC",
    "EndOfProcessing",
    "EventType",
    "ExecutionContext",
    "Graph",
    "InputStream",
    "MarkerEvent",
    "ModuleCodeFragment",
    "NewDeleteBucketSource",
    "Node",
    "NullReader",
    "NullSink",
    "NullSource",
    "Param",
    "Parameterized",
    "PySink",
    "ReadBinaryStream",
    "RecyclingBucketSource",
    "RelayNode",
    "SelectAll",
    "SinkEvents",
    "Stop",
    "StopWithError",
    "StuckReader",
    "Subgraph",
    "TimeCorrelatedDetectionEvent",
    "TimeReachedEvent",
    "TypePreservingRelayNode",
    "Unbatch",
    "WarningEvent",
    "byte_type",
    "compile_graph",
    "contains_type",
    "create_execution_context",
    "float32_type",
    "float64_type",
    "identifier_from_string",
    "int8_type",
    "int16_type",
    "int32_type",
    "int64_type",
    "is_same_type",
    "quote_string",
    "read_events_from_binary_file",
    "run_cpp_prog",
    "size_type",
    "string_type",
    "uint8_type",
    "uint16_type",
    "uint32_type",
    "uint64_type",
]
