/*
 * This file is part of libtcspc
 * Copyright 2019-2023 Board of Regents of the University of Wisconsin System
 * SPDX-License-Identifier: MIT
 */

#pragma once

// This file may be used in the future to include all the main headers.
// For now, it only serves to document the namespace and Doxygen groups.

/**
 * \mainpage libtcspc Documentation
 *
 * All public symbols are in the namespace \ref tcspc. See the Modules page for
 * a categorized list.
 */

/**
 * \brief libtcspc namespace.
 */
namespace tcspc {

/**
 * \defgroup events Event types
 *
 * \brief Event types.
 *
 * @{
 */

/**
 * \defgroup events-basic Simple events
 *
 * \brief Events with no specific meaning attached.
 */

/**
 * \defgroup events-device Device events
 *
 * \brief Raw event records generated by devices.
 */

/**
 * \defgroup events-timing Time tag and TCSPC events
 *
 * \brief Events representing time tags or TCSPC records.
 */

/**
 * \defgroup events-histogram Histogramming events
 *
 * \brief Events related to histogramming.
 */

/**
 * \defgroup events-testing Testing events
 *
 * \brief Events used for unit testing.
 */

/** @} */

/**
 * \defgroup processors Processors
 *
 * \brief Event processors.
 *
 * @{
 */

/**
 * \defgroup processors-basic Building block processors
 *
 * \brief Processors for basic processing tasks.
 */

/**
 * \defgroup processors-decode Decoding processors
 *
 * \brief Processors for decoding device events.
 */

/**
 * \defgroup processors-timing Basic time-tag processing
 *
 * \brief Processors for basic time-tag processing
 */

/**
 * \defgroup processors-histogram Histogramming processors
 *
 * \brief Processors for histogramming.
 */

/**
 * \defgroup processors-testing Testing processors
 *
 * \brief Processors for use in unit tests.
 */

/** @} */

/**
 * \defgroup timing-generators Timing generators
 *
 * \brief Timing generators for use with \ref generate_timings.
 */

/**
 * \defgroup data-mappers Data mappers
 *
 * \brief Datapoint mappers for use with \ref map_to_datapoints.
 */

/**
 * \defgroup bin-mapper Bin mappers
 *
 * \brief Bin mappers for use with \ref map_to_bins.
 */

/**
 * \defgroup overflow-strategies Overflow strategies
 *
 * \brief Tag types for specifying histogram bin overflow handling method.
 */

/**
 * \defgroup exceptions Exceptions
 *
 * \brief Exceptions representing errors generated by processors.
 */

/**
 * \defgroup metafunctions Metafunctions
 *
 * \brief Template metafunctions
 */

/**
 * \defgroup misc Miscellaneous
 *
 * \brief Everything else
 */

/**
 * \defgroup tbd TBD
 *
 * \brief Items whose future remains to be determined.
 */

} // namespace tcspc
