# This file is part of libtcspc
# Copyright 2019-2024 Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: MIT

name: CI

on:
  push: # All branches during early development.

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - uses: pre-commit/action@v3.0.1

  cpp-test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
          - macos-13  # x86_64
          - macos-14  # arm64
        compiler:
          - platform
          - clang
        exclude:
          - runner: macos-13
            compiler: clang  # Redundant with platform
          - runner: macos-14
            compiler: clang  # Redundant with platform
        include:
          - runner: ubuntu-22.04
            compiler: platform
            cxx: g++
            # TSan appears to have false positives in this configuration.
            sanitizers: address,undefined
            asan_opts: detect_leaks=1
          - runner: ubuntu-22.04
            compiler: clang
            cxx: clang++
            sanitizers: a+ub,thread
            asan_opts: detect_leaks=1
          - runner: ubuntu-24.04
            compiler: platform
            cxx: g++
            # I seem to get strage errors if ASan and UBSan are used together.
            sanitizers: address,undefined,thread
            asan_opts: detect_leaks=1
          - runner: ubuntu-24.04
            compiler: clang
            cxx: clang++
            sanitizers: a+ub,thread
            asan_opts: detect_leaks=1
          - runner: windows-2022
            compiler: platform
            cxx: cl
            opts: -Dcatch2:werror=false
            sanitizers: address
          - runner: windows-2022
            compiler: clang
            cxx: clang-cl
            opts: -Dcatch2:werror=false -Dgoogle-benchmark:werror=false
          - runner: windows-2022
            # Use /Z7 to be ccache-friendly (/Zi is not).
            debug_opts: -Dcpp_args=/Z7
          - runner: macos-13
            cxx: clang++
            sanitizers: a+ub,thread
          - runner: macos-14
            cxx: clang++
            sanitizers: a+ub,thread
    name: cpp-test-${{ matrix.runner }}-${{ matrix.cxx }}
    runs-on: ${{ matrix.runner }}
    env:
      CXX: ${{ matrix.cxx }}
      ASAN_OPTIONS: ${{ matrix.asan_opts }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache-cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install tools
        run: python -m pip install --upgrade pip meson ninja
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Cache ccache cache
        uses: actions/cache@v4
        with:
          # Currently there is no way to update the cache when hit
          # (https://github.com/actions/toolkit/issues/505). Instead, use
          # unique keys and restore from most recent.
          key: ccache-${{ matrix.runner }}-${{ matrix.cxx }}-${{ github.sha }}
          restore-keys: ccache-${{ matrix.runner }}-${{ matrix.cxx }}-
          path: ${{ github.workspace }}/.ccache-cache
      - name: Install ccache (Ubuntu)
        if: startsWith(matrix.runner, 'ubuntu-')
        run: |
          sudo apt-get install ccache
          ccache -z
          echo "CXX=ccache $CXX" >$GITHUB_ENV
      - name: Install ccache (macOS)
        if: startsWith(matrix.runner, 'macos-')
        run: |
          brew install ccache
          ccache -z
          echo "CXX=ccache $CXX" >$GITHUB_ENV
      - name: Install ccache (Windows)
        if: startsWith(matrix.runner, 'windows-')
        # Install ccache under the name cl.exe or clang-cl.exe and point to it
        # via CXX (see ccache MSVC instructions).
        run: |
          $version = '4.10'
          $url = "https://github.com/ccache/ccache/releases/download/v$version/ccache-$version-windows-x86_64.zip"
          $tempdir = Join-Path $([System.IO.Path]::GetTempPath()) $(New-Guid)
          $zip = Join-Path $tempdir ccache.zip
          $dist = Join-Path $tempdir ccache
          $exe = Join-Path $dist "ccache-$version-windows-x86_64\ccache.exe"
          New-Item -ItemType Directory -Path $tempdir | Out-Null
          Invoke-WebRequest -Uri $url -OutFile $zip
          Expand-Archive -Path $zip -DestinationPath $dist
          New-Item -ItemType Directory -Name ccache | Out-Null
          Copy-Item $exe -Destination '.\ccache\'
          Copy-Item $exe -Destination ".\ccache\$Env:CXX.exe"
          "CXX=$PWD\ccache\$Env:CXX" | Out-File -FilePath $Env:GITHUB_ENV
          .\ccache\ccache -z
      - name: Record start time
        shell: bash
        run: date +%s >.start-time

      - name: Configure release build
        run: >
          meson setup build-release --buildtype=release ${{ matrix.opts }}
          -Dgoogle-benchmark:tests=disabled -Dcatch2:tests=false
          -Dabridge_benchmarks=true
      - name: Test release build
        run: meson test -C build-release -v

      - name: Configure with ASan+UBSan
        if: contains(matrix.sanitizers, 'a+ub')
        run: >
          meson setup build-asan-ubsan --buildtype=debug ${{ matrix.opts }}
          ${{ matrix.debug_opts }} -Dbenchmarks=disabled -Dcatch2:tests=false
          -Db_lundef=false -Db_sanitize=address,undefined
      - name: Test with ASan+UBSan
        if: contains(matrix.sanitizers, 'a+ub')
        run: meson test -C build-asan-ubsan -v

      - name: Configure with ASan
        if: contains(matrix.sanitizers, 'address')
        # With MSVC, vector/string annotations for ASan fail due to mismatch
        # between Catch2 and libtcspc. Disable these for now.
        run: >
          meson setup build-asan --buildtype=debug ${{ matrix.opts }}
          ${{ matrix.debug_opts }} -Dbenchmarks=disabled -Dcatch2:tests=false
          -Db_lundef=false -Db_sanitize=address
          -Dcpp_args='-D_DISABLE_VECTOR_ANNOTATION -D_DISABLE_STRING_ANNOTATION'
      - name: Test with ASan
        if: contains(matrix.sanitizers, 'address')
        run: meson test -C build-asan -v

      - name: Configure with UBSan
        if: contains(matrix.sanitizers, 'undefined')
        run: >
          meson setup build-ubsan --buildtype=debug ${{ matrix.opts }}
          ${{ matrix.debug_opts }} -Dbenchmarks=disabled -Dcatch2:tests=false
          -Db_lundef=false -Db_sanitize=undefined
      - name: Test with UBSan
        if: contains(matrix.sanitizers, 'undefined')
        run: meson test -C build-ubsan -v

      - name: Configure with TSan
        if: contains(matrix.sanitizers, 'thread')
        run: >
          meson setup build-tsan --buildtype=debug ${{ matrix.opts }}
          ${{ matrix.debug_opts }} -Dbenchmarks=disabled -Dcatch2:tests=false
          -Db_lundef=false -Db_sanitize=thread
      - name: Test with TSan
        if: contains(matrix.sanitizers, 'thread')
        run: meson test -C build-tsan -v

      # Note: Memory Sanitizer has false positives unless libc++ is
      # instrumented; skip for now.

      - name: Configure debug build
        run: >
          meson setup build-debug --buildtype=debug ${{ matrix.opts }}
          ${{ matrix.debug_opts }} -Dbenchmarks=disabled -Dcatch2:tests=false
      - name: Test debug build
        run: meson test -C build-debug -v

      - name: Configure C++20 build
        run: >
          meson setup build-cpp20 --buildtype=release ${{ matrix.opts }}
          -Dcpp_std=c++20
          -Dgoogle-benchmark:tests=disabled -Dcatch2:tests=false
      - name: Test C++20 build
        run: meson test -C build-cpp20 -v

      - name: Exercise benchmarks
        run: ninja -C build-release benchmark

      - name: Clean up ccache cache
        shell: bash
        run: |
          PATH="$PWD/ccache:$PATH"
          elapsed=$(($(date +%s) - $(<.start-time) + 10))s
          ccache --evict-older-than $elapsed
          ccache -sv

  cpp-analyze:
    runs-on: ubuntu-24.04
    env:
      CXX: clang++
    steps:
      - uses: actions/checkout@v4
        with:
          path: libtcspc
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install tools
        run: python -m pip install --upgrade pip meson ninja

      - run: clang-tidy --version

      - name: Install ctcache
        uses: actions/checkout@v4
        with:
          repository: matus-chochlik/ctcache
          # Significant bugs have been fixed since the last release (1.1.0).
          ref: 'debfea68152c5221d8f409cbef85dc5d0f98071d'  # Apr 30 2024
          path: ctcache

      - name: Set up ctcache
        run: |
          clang-tidy --version >clang-tidy-conf
          # Importantly, ctcache does not currently add the clang-tidy config
          # to the hash, so we need to invalidate the cache if there are
          # changes.
          # Ideally we would use clang-tidy --dump-config, but that depends on
          # the input file. Since this is for bulk cache validity checking,
          # instead simply aggregate all the .clang-tidy files in the tree.
          find . -name .clang-tidy -exec sh \
              -c 'echo "{}" >>clang-tidy-conf; cat "{}" >>clang-tidy-conf' \;

          cfgdir=$HOME/.config/ctcache
          cfg=$cfgdir/ctcache.conf
          mkdir -p $cfgdir
          echo "CTCACHE_CLANG_TIDY=$(command -v clang-tidy)" >$cfg
          echo 'CTCACHE_CLANG_TIDY_OPTS=(--quiet --use-color)' >>$cfg
          # Warning: only the above 2 variables work when set in ctcache.conf;
          # they are settings for the wrapper script 'clang-tidy'. Settings for
          # 'clang-tidy-cache' itself require 'export' if set in ctcache.conf.

          # Put the wrapper script on PATH, now that we are done with querying
          # the unwrapped clang-tidy.
          echo ${{ github.workspace }}/ctcache >>$GITHUB_PATH

      - name: Cache ctcache cache
        uses: actions/cache@v4
        with:
          # Currently there is no way to update the cache when hit
          # (https://github.com/actions/toolkit/issues/505). Instead, use
          # unique keys and restore from most recent. Never match if the
          # clang-tidy version or config has changed. We do not bother to prune
          # the cache after running, because clang-tidy output is small.
          key: ctcache-${{ hashFiles('clang-tidy-conf') }}-${{ github.sha }}
          restore-keys: ctcache-${{ hashFiles('clang-tidy-conf') }}-
          path: ${{ github.workspace }}/.cache/ctcache

      - name: Configure build
        working-directory: libtcspc
        run: meson setup builddir --buildtype=release

      - name: Run clang-tidy
        working-directory: libtcspc
        env:
          CTCACHE_DIR: ${{ github.workspace }}/.cache/ctcache
        run: ninja -C builddir clang-tidy

  py-test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          # Only test with Python versions available on the runners.
          - runner: ubuntu-latest
            py_versions: 3.10 3.11 3.12
          - runner: windows-latest
            py_versions: 3.10 3.11 3.12
          - runner: macos-latest
            py_versions: 3.11 3.12 3.13

    name: py-test-${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    steps:
      - run: uname -m
        if: ${{ ! startsWith(matrix.runner, 'windows-') }}

      - uses: actions/checkout@v4
      - uses: fjwillemsen/setup-nox2@v3.0.0
      - uses: ilammy/msvc-dev-cmd@v1

      - run: nox -p ${{ matrix.py_versions }}

  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install tools
        run: python -m pip install --upgrade pip meson ninja
      - name: Install Doxygen 1.11
        run: |
          curl -LO https://www.doxygen.nl/files/doxygen-1.11.0.linux.bin.tar.gz
          tar xf doxygen-1.11.0.linux.bin.tar.gz
          echo $PWD/doxygen-1.11.0/bin >>$GITHUB_PATH

      - name: Configure
        run: >
          meson setup builddir -Dtests=disabled -Dexamples=disabled
          -Dbenchmarks=disabled -Ddocs=enabled -Ddocs_werror=true
      - name: Build
        run: ninja -C builddir docs/apidoc

      # TODO Publish, but we first need to decide how to combine C++ API docs
      # with (yet-to-be-created) Python docs.
